### ISSUE TITLE
Apache doesn't start if PS_INSTALL_AUTO=1

### ISSUE THREAD

**Issue by esindger** [PrestaShop/docker#104]
Hello,
I have a problem with starting apache if the `PS_INSTALL_AUTO` option is set on. It looks like infinite loading of the page `http://172.18.0.3:8080/`.

Everything is ok when I install PS manually.

OS: `macOS Hight Sierra 10.13`
Docker: `17.09.0-ce-mac35 (19611)`

My docker-compose:
```yml
version: '3'
services:
  ps_mysql:
    image: mysql:latest
    container_name: ps_mysql
    restart: unless-stopped
    environment:
      - MYSQL_USER=ps_user
      - MYSQL_PASSWORD=ps_password
      - MYSQL_ROOT_PASSWORD=root

  ps_1724:
    image: prestashop/prestashop:1.7.2.4
    container_name: ps_1724
    restart: unless-stopped
    working_dir: /var/www/html
    ports:
      - 8080:80
    links:
      - ps_mysql
    environment:
      - DB_SERVER=ps_mysql
      - DB_NAME=ps_1724
      - DB_USER=ps_user
      - DB_PASSWD=ps_password
      - PS_INSTALL_AUTO=1
      - PS_ERASE_DB=1
      - PS_FOLDER_ADMIN=admin0
      - PS_FOLDER_INSTALL=install0
      - PS_LANGUAGE=en
      - PS_COUNTRY=uk
      - PS_DEV_MODE=true
      - PS_HANDLE_DYNAMIC_DOMAIN=1
      - ADMIN_MAIL=demo@prestashop.com
      - ADMIN_PASSWD=prestashop_demo

```
Log (here is only prestashop container part):
```
$ docker-compose up
Creating network "pst_default" with the default driver
Creating ps_mysql ... 
Creating ps_mysql ... done
Creating ps_1724 ... 
Creating ps_1724 ... done
Attaching to ps_mysql, ps_1724
pst-mysql   | Initializing database
ps_1724     | 
ps_1724     | * Reapplying PrestaShop files for enabled volumes ...
ps_1724     | /tmp/docker_run.sh: 15: [: Illegal number: true
ps_1724     | 
ps_1724     | * Renaming install folder as install0 ...
ps_1724     | 
ps_1724     | * Renaming admin folder as admin0 ...
pst-mysql   | 2017-12-04T11:01:33.282350Z 0 [Note] End of list of non-natively partitioned tables
ps_1724     | 
ps_1724     | * Waiting for confirmation of MySQL service startup
ps_1724     | 
ps_1724     | * Installing PrestaShop, this may take a while ...
ps_1724     | 
ps_1724     | * Drop & recreate mysql database...
ps_1724     | 
ps_1724     | * Almost ! Starting Apache now
ps_1724     | 
ps_1724     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
ps_1724     | AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.18.0.3. Set the 'ServerName' directive globally to suppress this message
ps_1724     | [Mon Dec 04 11:02:04.643578 2017] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
ps_1724     | [Mon Dec 04 11:02:04.643694 2017] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
```

Will appreciate for any help.
