### ISSUE TITLE
Docker PS_INSTALL_AUTO=1 Not working! :fire:

### ISSUE THREAD

**Issue by retyui** [PrestaShop/docker#111]
I'm trying to set up prestashop automatic mode using `PS_INSTALL_AUTO=1` env.
But after doing the `docker-compouse up`,  it does not work (empty database)! although there were no errors in the log :(
I have to execute a command manually:
```bash
sudo docker exec -it __ID__ php /var/www/html/install-dev/index_cli.php --domain="prestashop.local" --db_server=mysql:3306 --db_name="ps17" --db_user=docker --db_password=docker --prefix="ps_" --firstname="John" --lastname="Doe" --password=admin@admin.com --email="admin@admin.com" --language=es --country=gb --newsletter=0 --send_email=0
```

## My compouse file:
```yml
mariadb-ps17:
  image: mariadb
  ports:
    - 3306:3306
  env_file:
   - .env
ps_17:
  image: prestashop/prestashop:1.7-7.0
  links:
    - mariadb-ps17:mysql
  volumes:
   - ./www/themes:/var/www/html/themes
   - ./www/modules:/var/www/html/modules
   - ./www/override:/var/www/html/override
   - ./server_logs:/var/log
   - ./server_logs/php-fpm:/var/log/php-fpm
  ports:
   - "80:80"
  env_file:
   - .env
```
## .env file
```bash
MYSQL_ROOT_PASSWORD=root
MYSQL_DATABASE=ps17
MYSQL_USER=docker
MYSQL_PASSWORD=docker
DB_SERVER=mysql
DB_NAME=ps17
DB_USER=docker
DB_PASSWD=docker
DB_PREFIX=ps_
PS_LANGUAGE=es
PS_COUNTRY=gb
PS_DEV_MODE=1
PS_FOLDER_ADMIN=admin-dev
PS_FOLDER_INSTALL=install-dev
PS_INSTALL_AUTO=1
PS_DOMAIN=prestashop.local
PS_HANDLE_DYNAMIC_DOMAIN=0
ADMIN_PASSWD=test@test.com
ADMIN_MAIL=test@test.com
```
## Log:
https://gist.github.com/anonymous/f49884159b25c85a92503c600828a6d2
