### ISSUE TITLE
Can't access prestashop on bridge network

### ISSUE THREAD

**Issue by daviddumon** [PrestaShop/docker#113]
Hello,

I've setup prestashop in a docker container. Here is my compose file :

```
version: '3'
services:
  myproject-mysql:
    image: mysql:$mysql_version
    container_name: myproject-mysql
    ports:
     - 3306:3306
    environment:
      - MYSQL_USER=myproject
      - MYSQL_PASSWORD=admin
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_DATABASE=prestashop

  myproject-prestashop:
    image: prestashop/prestashop:$ps_version
    depends_on:
      - myproject-mysql
    container_name: myproject-prestashop
    working_dir: /var/www/html
    ports:
      - 8080:80
    links:
      - myproject-mysql
    volumes:
      - "./prestashopmyproject:/var/www/html/modules/prestashopmyproject"
    environment:
     - DB_SERVER=myproject-mysql
     - DB_NAME=prestashop
     - DB_USER=myproject
     - DB_PASSWD=admin
     - PS_INSTALL_AUTO=1
     - PS_DEV_MODE=1
     - PS_ERASE_DB=1
     - PS_FOLDER_ADMIN=admin-myproject
     - PS_DOMAIN=localhost:8080
     - PS_SHOP_URL=localhost:8080
     - PS_LANGUAGE=fr
     - PS_COUNTRY=fr
     - ADMIN_MAIL=dev@myproject.io
     - ADMIN_PASSWD=password
     - PS_FOLDER_INSTALL=install-myproject
```
I've setup a second docker compose which run a node project. This project need to access the prestashop api @ myproject-prestashop/api. Here is the configuration file :

```
version: '3'
services:
  myproject-webapp-builder:
    image: node:carbon
    user: "root"
    container_name: myproject-webapp-builder
    network_mode: "host"
    working_dir: /home/node/app
    ports:
      - 3335:3335
    volumes:
      - ./:/home/node/app
    command: "npm run docker"
```

When i access the prestashop from the host on localhost:8080, everything works as intented. I need to keep the prestashop exposed to the host. But on the node app, I can't access it.

Here is my network :

```
[
    {
        "Name": "myproject_default",
        "Id": "363af0901a281d5c89c2bf9895e56e89e19cad188681adfa667a7a192bd8db68",
        "Created": "2018-02-21T08:14:30.27854204Z",
        "Scope": "local",
        "Driver": "bridge",
        "EnableIPv6": false,
        "IPAM": {
            "Driver": "default",
            "Options": null,
            "Config": [
                {
                    "Subnet": "172.18.0.0/16",
                    "Gateway": "172.18.0.1"
                }
            ]
        },
        "Internal": false,
        "Attachable": true,
        "Ingress": false,
        "ConfigFrom": {
            "Network": ""
        },
        "ConfigOnly": false,
        "Containers": {
            "3a0b95e15906ee3eb12f11e05cb7318f4ccd334e01a4dfda5511ca786a2cd4ac": {
                "Name": "myproject-prestashop",
                "EndpointID": "5c7f4ec0d525a6cabd23ba7c2d8fe4a4d887fad25b7dd7d24ca75f688d1a26f5",
                "MacAddress": "02:42:ac:12:00:03",
                "IPv4Address": "172.18.0.3/16",
                "IPv6Address": ""
            },
            "421256a54ee0ea0da0c9cc0f46221aee7818f22d00943dde8ffd66af7a39e4aa": {
                "Name": "myproject-mysql",
                "EndpointID": "b49717e3c0f280967fb2de0dc5edfea29bbef72d8ea21e37f5f119b3b2c36213",
                "MacAddress": "02:42:ac:12:00:02",
                "IPv4Address": "172.18.0.2/16",
                "IPv6Address": ""
            },
            "4ee865aff1f7ce546225676e5c8a3be6df3a87f7446958723a53aff6aac44900": {
                "Name": "myproject-webapp-builder",
                "EndpointID": "ebe27e16dda2dff66577522cd9673bbea4f93b916abee1026b28f392d9d72c67",
                "MacAddress": "02:42:ac:12:00:04",
                "IPv4Address": "172.18.0.4/16",
                "IPv6Address": ""
            }
        },
        "Options": {},
        "Labels": {
            "com.docker.compose.network": "default",
            "com.docker.compose.project": "myproject"
        }
    }
]
```

If i connect to the node docker whis docker exec -ti myproject-webapp-builder bash, i can see the prestashop container :

```
root@4ee865aff1f7:/home/node/app# ping myproject-prestashop
PING myproject-prestashop (172.18.0.3): 56 data bytes
64 bytes from 172.18.0.3: icmp_seq=0 ttl=64 time=0.358 ms
```
But i cannot curl it :

```
root@4ee865aff1f7:/home/node/app# curl myproject-prestashop:8080 -I
curl: (7) Failed to connect to myproject-prestashop port 8080: Connection refused

root@4ee865aff1f7:/home/node/app# curl myproject-prestashop -I     
HTTP/1.0 302 Found
Date: Wed, 21 Feb 2018 08:57:19 GMT
Server: Apache/2.4.10 (Debian)
Location: http://localhost:8080/index.php?
Connection: close
Content-Type: text/html; charset=utf-8
```

I've seen the env variable PS_HANDLE_DYNAMIC_DOMAIN, and my guess is that there is something related to it, but I don't understand how to use it.

Thanks for the help
