### ISSUE TITLE
Recursive write permissions for volume "/var/www/html/modules"

### ISSUE THREAD

**Issue by benedictdudel** [PrestaShop/docker#116]
Currently I am working with the following `docker-compose.yml` file:

```
version: "3"

services:
  mariadb:
    image: mariadb:10.3
    container_name: mariadb
    env_file:
      - .env

  prestashop:
    image: prestashop/prestashop:1.7
    container_name: prestashop
    volumes:
      - ./src:/var/www/html/modules/mylittlemodule
    ports:
      - 8080:80
    env_file:
      - .env
```

But when installing PrestaShop via GUI and I see the following message:

`Recursive write permissions for www-data user on ~/modules/`

So I tried to change permissions for the directory (inside the container) by executing the following command:

`chown -R www-data:www-data /var/www/html/modules`

But this didn't fixed the error, I am still seeing the same error. Any chance to solve the issue?
