### ISSUE TITLE
.htaccess missing

### ISSUE THREAD

**Issue by roest01** [PrestaShop/docker#120]
after building this image, .htaccess file is missing.
aside from home, no URL's working.

Can the function `Tools14:generateHtaccess` called after build in any way?

```
version: '2'
services:
  prestashop:
    image: prestashop/prestashop
    environment:
      PS_DOMAIN: XXX
      DB_SERVER: XXX
      DB_PORT: '3306'
      DB_NAME: XXX
      DB_USER: XXX
      DB_PASSWD: XXX
      DB_PREFIX: ps_
      ADMIN_MAIL: admin@XXXX.de
      ADMIN_PASSWD: XXXX
      PS_LANGUAGE: de
      PS_COUNTRY: de
      PS_INSTALL_AUTO: '0'
      PS_ERASE_DB: '0'
      PS_DEV_MODE: '0'
      PS_HOST_MODE: '0'
      PS_FOLDER_ADMIN: adminXYZ
      PS_FOLDER_INSTALL: installDisabled
      PS_VERSION: 1.7.3.0
    stdin_open: true
    volumes:
    - ps-config:/var/www/html/app/config
    - ps-img:/var/www/html/img
    - ps-modules:/var/www/html/modules
    - ps-themes:/var/www/html/themes
    tty: true
    labels:
      io.rancher.container.pull_image: always

```
