### ISSUE TITLE
Can use Prestashop with docker-compose

### ISSUE THREAD

**Issue by noyessie** [PrestaShop/docker#125]
Please someone can help me. I want to install prestashop using docker compose. this is my compose file:

```
version: '3'
services:
  mysql:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=solidmaison
      - MYSQL_DATABASE=solidmaison
      - MYSQL_USER=prestashop
      - MYSQL_PASSWORD=prestashop
    ports:
      - "3306:3306"
    volumes:
      - /var/lib/mysql:/data/mysql

  prestashop:
    image: prestashop/prestashop
    restart: always
    ports:
      - "80:80"
    depends_on:
      - mysql
    environment:
      - DB_SERVER=mysql
      - DB_USER=prestashop
      - DB_PASSWD=prestashop
      - DB_PREFIX=sm
      - DB_NAME=solidmaison
      - PS_INSTALL_AUTO=1
      - PS_LANGUAGE=fr
      - ADMIN_MAIL=hubertnoyessie@gmail.com
      - ADMIN_PASSWD=solidmaison
    volumes:
      - /tmp/data-ps/:/data/solidmaison-ps
    links:
      - mysql


```

But i always have response  `prestashop_1  | * Waiting for confirmation of MySQL service startup
` from prestashop service.
