### ISSUE TITLE
Prestashop + Let's Encrypt Certbot - periodical INVALID_SSL_CERTIFICATE error

### ISSUE THREAD

**Issue by adamczykjac** [PrestaShop/docker#126]
Hi all containerized Prestashoppers ;)

I've been hitting this wall since some weeks now and my idea sources slowly get depleted...

I'm trying to setup a Docker Compose setup for my Prestashop instance, with derived Docker image and overriden `docker_run.sh` to install and run Certbot with Apache plugin, in order to obtain Let's Encrypt SSL certificates. Everything works well - I can obtain the certificates with Certbot, which additionally redirects the whole HTTP traffic to HTTPS, and after finally turning the SSL on in PS settings and enabling it for every website, I get the expected result with my shop instance SSL-secured. Yay!

The hard things come from this point on - after some nondeterministic time elapsed after certificate installation (about 1-2 hours), I periodically spot some strange behaviour - the URL gets switched to the IP of my machine - `X.X.X.X:80/index.php`, followed by the expected browser's error about Invalid SSL Certificate. As we all know it, they are given to domain names, not IP addresses. 

I've been tweaking this setup with all possible configurations on the Prestashop site: turning off canonical link redirection, switching between 301 and 302 redirect (shop's URL was always correct and pointing to the domain name). I know it should not bring any effect by definition, but this odd behaviour pushed me to testing literally everything I could think of.

Here's the `docker-compose.yml` setup:
```
version: '3.2'
services:
  shop:
    container_name: apiart-shop
    env_file: ./env/${CONFIG}/shop.env
    depends_on:
      - db
    image: "szymonlyszkowski/apiart-prestashop:${APIART_VERSION}"
    ports:
      - "80:80"
      - "443:443"
    environment:
      DB_SERVER: db
    volumes:
      - /var/backups:/var/backups
      - /etc/letsencrypt:/etc/letsencrypt
      - /etc/prestashop/cookie:/etc/prestashop/cookie
  db:
    container_name: apiart-db
    env_file: ./env/${CONFIG}/db.env
    image: "mysql:5.7"
    volumes:
    - /var/backups:/var/backups
```
The env file I'm using in this scenario looks like this:
```
PS_FOLDER_ADMIN=admin974otxap1
PS_FOLDER_INSTALL=install334f2xls
ADMIN_MAIL=test@test.pl
ADMIN_PASSWD=test1234
PS_DOMAIN=some.domain.pl
PS_HANDLE_DYNAMIC_DOMAIN=1
DB_USER=apiart
DB_PASSWD=apiart
DB_NAME=apiart
PS_INSTALL_AUTO=1
PS_LANGUAGE=pl
PS_COUNTRY=pl
CONFIG=staging
```
Docker image is being built based on:
```
FROM prestashop/prestashop:1.6-7.0

COPY scripts/docker_run.sh /tmp/_docker_run.sh
RUN chmod +x /tmp/*.sh

# Getting certbot - it will be installed during first run
RUN wget -q --directory-prefix=/root/ https://dl.eff.org/certbot-auto
RUN chmod a+x /root/certbot-auto

VOLUME /var/backups

ENTRYPOINT /tmp/_docker_run.sh
```

and last but not least, the overriden `docker_run.sh` file:
```
#!/usr/bin/env bash
set -e

/root/certbot-auto run -n --apache -d ${PS_DOMAIN} --no-bootstrap --agree-tos --email ${ADMIN_MAIL}
  # Kill running Apache2 processes in order to not let container exit after certbot finishes
  pkill apache2
fi

# Launch Prestashop
/tmp/docker_run.sh
```
Has any of you seen something similar?
