### ISSUE TITLE
Impossible to go further the installation

### ISSUE THREAD

**Issue by pasqwa** [PrestaShop/docker#173]
Hi,

I used the commands from docker hub to create mysql and prestashop containers but I can't go further than the registration page where I must input the domain, ID, password,... during installation.
The page is still running but nothing happen after 30 min.
I try on several machine but same issue.

Here is the commands :

```
# create a network for containers to communicate
$ docker network create prestashop-net
# launch mysql 5.7 container
$ docker run -ti --name some-mysql --network prestashop-net -e MYSQL_ROOT_PASSWORD=admin -p 3307:3306 -d mysql:5.7
# launch prestashop container
$ docker run -ti --name some-prestashop --network prestashop-net -e DB_SERVER=some-mysql -p 8080:80 -d prestashop/prestashop

```

I also try with docker-compose and install_auto enable but it never end.

docker-compose.yml :
```

version: "3"

services:
  mysql:
    image: mysql/mysql-server:5.7
    restart: always
    ports:
      - 33060:3306
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}

  prestashop_1.7.3:
    image: prestashop/prestashop:1.7.3
    depends_on:
      - mysql
    ports:
      - 8080:80
    volumes:
      - .:/var/www/html/modules/${PS_MODULE_NAME}
    environment:
      - DB_SERVER=mysql
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - PS_ERASE_DB=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN}
      - PS_DOMAIN=${PS_DOMAIN}:8083
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
```

.env :

```
# Database
DB_USER=username
DB_PASSWD=password
DB_NAME=prestashop

# Prestashop
PS_DOMAIN=localhost
PS_DEV_MODE=1
PS_FOLDER_ADMIN=adminPS
PS_MODULE_NAME=testmodule
PS_LANGUAGE=en
PS_COUNTRY=GB
```

Thanks for your support.

Giuseppe
