### ISSUE TITLE
Permission denied in Autoload

### ISSUE THREAD

**Issue by lfirek** [PrestaShop/docker#189]
Hello,

I purged docker images and for latest image `prestashop/prestashop:1.7-7.0-apache` getting error when try to manual install. 

For older images all works well ex. `prestashop/prestashop:1.7.5.1`

Error
```
prestashop    | [Fri Oct 25 20:41:07.185481 2019] [:error] [pid 33] [client 172.19.0.1:41190] PHP Warning:  require_once(/var/www/html/var/cache/prod/namespaced_class_stub.php): failed to open stream: Permission denied in /var/www/html/classes/PrestaShopAutoload.php on line 160, referer: http://localhost:8080/install1234/index.php
prestashop    | [Fri Oct 25 20:41:07.185557 2019] [:error] [pid 33] [client 172.19.0.1:41190] PHP Fatal error:  require_once(): Failed opening required '/var/www/html/var/cache/prod/namespaced_class_stub.php' (include_path='/var/www/html/vendor/pear/pear_exception:/var/www/html/vendor/pear/console_getopt:/var/www/html/vendor/pear/pear-core-minimal/src:/var/www/html/vendor/pear/archive_tar:.:/usr/local/lib/php') in /var/www/html/classes/PrestaShopAutoload.php on line 160, referer: http://localhost:8080/install1234/index.php
```

docker-compose
```
version: '2'

services:
    prestashop:
        container_name: prestashop
        image: prestashop/prestashop:1.7-7.0-apache
        environment:
        - DB_SERVER=database
        - DB_USER=root
        - DB_PASSWD=admin
        - PS_DEV_MODE=true
        - PS_FOLDER_ADMIN=admin1234
        - PS_FOLDER_INSTALL=install1234
        - PS_DOMAIN=localhost:8080
        depends_on:
        - database
        ports:
        - 8080:80
        restart: always
    database:
        container_name: database
        image: mysql:5.7.24
        environment:
        - MYSQL_ROOT_PASSWORD=admin
        ports:
        - 3306:3306
    phpmyadmin:
        container_name: phpmyadmin
        image: phpmyadmin/phpmyadmin
        depends_on:
        - database
        environment:
        - PMA_HOST=database
        ports:
        - 8090:80
```
