### ISSUE TITLE
prestashop/prestashop:1.6-5.6-apache PHP Error

### ISSUE THREAD

**Issue by LithMage** [PrestaShop/docker#211]
Hi,

i am getting 
```php
PHP Fatal error:  Call to undefined function imagecreatefromjpeg() in /var/www/html/classes/ImageManager.php on line 486
```
when trying to use docker-compose up with one of the services for prestashop/prestashop:1.6-5.6-apache

my compose file is setup like this
```yml
version: "3"

services:
  demo_mysql:
    image: mysql/mysql-server:5.7
    restart: always
    volumes:
      - ./sql_data:/var/lib/mysql
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWD}
      - MYSQL_DATABASE=${DB_NAME}

  prestashop_1.6:
    image: prestashop/prestashop:1.6-5.6-apache
    depends_on:
      - demo_mysql
    ports:
      - 8116:80
    volumes:
      - ./module_ps16:/var/www/html/modules/${PS_MODULE_NAME}
    environment:
      - DB_SERVER=demo_mysql
      - DB_PREFIX=ps16_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - ADMIN_MAIL=${ADMIN_MAIL}
      - ADMIN_PASSWD=${ADMIN_PASSWD}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN_16}
      - PS_DOMAIN=${PS_DOMAIN_16}
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed

  prestashop_1.7:
    image: prestashop/prestashop:1.7-7.2-apache
    depends_on:
      - demo_mysql
    ports:
      - 8117:80
    volumes:
      - ./module_ps17:/var/www/html/modules/${PS_MODULE_NAME}
    environment:
      - DB_SERVER=demo_mysql
      - DB_PREFIX=ps17_
      - PS_DEV_MODE=${PS_DEV_MODE}
      - PS_INSTALL_AUTO=1
      - DB_USER=${DB_USER}
      - DB_PASSWD=${DB_PASSWD}
      - DB_NAME=${DB_NAME}
      - PS_FOLDER_ADMIN=${PS_FOLDER_ADMIN_17}
      - PS_DOMAIN=${PS_DOMAIN_17}
      - PS_LANGUAGE=${PS_LANGUAGE}
      - PS_COUNTRY=${PS_COUNTRY}
      - PS_FOLDER_INSTALL=installed
```

the second prestashop 1.7 version works just fin and starts without any issues.

P.S. I did try at first just prestashop/prestashop:1.6 but got this same error.
