### ISSUE TITLE
Upgrade prestashop with docker

### ISSUE THREAD

**Issue by mabed-fr** [PrestaShop/docker#286]
Hello,

I am currently using PrestaShop with Docker-Compose and before going further I would like to test the update of PrestaShop.

Currently I use the tags of images to move from one version of prestashop to another but the version does not change in the backoffice.

Example:

From:

```
  prestashop:
    image: prestashop/prestashop:1.7.7.8-apache
    container_name: prestashop
    volumes:
      - /docker/volumes/prestashop:/var/www/html:rw
    restart: always
    environment:
      PS_DEV_MODE: 0
      DB_SERVER: db-prestashop
      DB_USER: root
      DB_PASSWD: **************
      DB_NAME: prestashop
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: prestashop.exemple.fr
      PS_LANGUAGE: fr
      PS_COUNTRY: FR
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: me@me.fr
      ADMIN_PASSWD:   **************
      PS_INSTALL_DB: 0
    depends_on:
      - "db-prestashop"
```

to: (with docker-compose up -d)

```
  prestashop:
    image: prestashop/prestashop:1.7.8.2-apache
    container_name: prestashop
    volumes:
      - /docker/volumes/prestashop:/var/www/html:rw
    restart: always
    environment:
      PS_DEV_MODE: 0
      DB_SERVER: db-prestashop
      DB_USER: root
      DB_PASSWD: **************
      DB_NAME: prestashop
      PS_INSTALL_AUTO: 0
      PS_DOMAIN: prestashop.exemple.fr
      PS_LANGUAGE: fr
      PS_COUNTRY: FR
      PS_ENABLE_SSL: 1
      ADMIN_MAIL: me@me.fr
      ADMIN_PASSWD:   **************
      PS_INSTALL_DB: 0
    depends_on:
      - "db-prestashop"
```

Here is my configuration: 

Informations
info_outline Informations de configuration

Ces informations sont importantes lors de l'envoi de rapports de bugs sur la Forge, ou l'explication d'un problèmes sur notre forum.
info_outline Informations sur votre serveur

> Informations sur votre serveur Linux #1 SMP Debian 5.10.70-1 (2021-09-30) x86_64
> 
> > Version du logiciel serveur : Apache/2.4.51 (Debian)
> > 
> > Version de PHP : 7.4.26
> > 
> > Limite de mémoire : 256M
> > 
> > Temps maximal d'exécution : 30
> > 
> > Taille max. pour envoi de fichiers : 20M
> > info_outline Informations sur la base de données
> > 
> > Version de MySQL : 5.7.36
> > 
> > Serveur MySQL : db-prestashop:3306
> > 
> > Nom MySQL : prestashop
> > 
> > Utilisateur MySQL : root
> > 
> > Préfixe des tables : ps_
> > 
> > Moteur MySQL : InnoDB
> > 
> > Connecteur MySQL : DbPDO
