### ISSUE TITLE
installation is triggered at every container start

### ISSUE THREAD

**Issue by krodelabestiole** [PrestaShop/docker#381]
Hi I'm trying to use a dockerised prestashop from an existing install.
Since I work on custom theme, modules and probably _overrides_ I would like to persist `/var/www/html`.

I have my existing database running, but every time I start prestashop it triggers the installer.
The first time is ok I guess because it has to create files.

Then the next times, prestashop will create an `install.lock` file and will fail to get over the installation because the admin `Backoffice` directory is not empty.
Then it will run into this `Another setup is currently running` issue.

I bind `/var/www/html` to a local directory :
```
    volumes:
      - type: bind
        source: ./src
        target: /var/www/html
    environment:
      - PS_DEV_MODE=0
      - PS_INSTALL_AUTO=0
      - TZ
      - DB_SERVER=db
      - DB_NAME=${MYSQL_DATABASE}
      - DB_USER=${MYSQL_USER}
      - DB_PASSWORD=${MYSQL_PASSWORD}
      - DB_PREFIX=prstshp_
      - PS_ALL_LANGUAGES=1
      - PS_FOLDER_ADMIN=Backoffice
      - PS_ENABLE_SSL=0
```
Unfortunately the `PS_INSTALL_AUTO` doesn't seem to do anything.

I don't see what triggers the installation and how to disable it, based on the doc I could find :
https://devdocs.prestashop-project.org/8/basics/installation/environments/docker/

What would be the way to totally disable the installer ?
