### ISSUE TITLE
PS_INSTALL_AUTO: 1 not working - PHP Fatal error:  Uncaught Symfony\Component\Filesystem\Exception\IOException: Failed to create "/var/www/html/var/cache/prod/": mkdir(): Permission denied in /var/www/html/vendor/symfony/symfony/src/Symfony/Component/Filesystem/Filesystem.php:105

### ISSUE THREAD

**Issue by voran** [PrestaShop/docker#385]
We are observing the issue using the following minimum docker-compose.yml based on https://devdocs.prestashop-project.org/8/basics/installation/environments/docker/#automatically-install-prestashop-with-test-data

The issue is observed with docker images versions `8.1.3-apache`, `8.1.5-apache`  but seems to be resolved in `latest`. 

Removing the volumes declaration from the presta ccontainer does not solve the issue.

docker-compose.yml:
```
version: '3'
services:
  mysql:
    container_name: some-mysql
    image: mysql:5.7.41
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: prestashop
    networks:
      - prestashop_network
    volumes:
      - dbdata:/var/lib/mysql
  prestashop:
    container_name: prestashop
    image: prestashop/prestashop:8.1.3-apache
    depends_on:
      - mysql
    ports:
      - 8080:80
    environment:
      DB_SERVER: some-mysql
      DB_NAME: prestashop
      DB_USER: root
      DB_PASSWD: admin
      PS_INSTALL_AUTO: '1'
      ADMIN_MAIL: dev@releva.ai
      ADMIN_PASSWD: prestarocks1
      PS_DOMAIN: localhost:8085
    networks:
      - prestashop_network
    volumes:
      - psdata:/var/www/html
networks:
  prestashop_network:
volumes:
  psdata:
  dbdata:
```
