### ISSUE TITLE
Prestashop installation > unable to connect to tcp://api.segment.io:80 (Connection timed out)

### ISSUE THREAD

**Issue by hamadodene** [PrestaShop/docker#409]
I'm encountering a particular issue:
I'm setting up PrestaShop on Kubernetes using my base Helm chart with prestashop docker image. I was able to configure several PrestaShop instances without issues, but at some point, I started getting this error when trying to install new PrestaShop instances:

```
[Thu Nov 28 15:07:18.988235 2024] [php7:warn] [pid 25] [client 172.20.136.27:35114] PHP Warning:  pfsockopen(): unable to connect to tcp://api.segment.io:80 (Connection timed out) in /var/www/html/modules/ps_metrics/vendor/segmentio/analytics-php/lib/Segment/Consumer/Socket.php on line 49, referer:
```

This is my helm chart config:

```
containers:
  - name: prestashop-auto
    image:
      repository: prestashop/prestashop
      pullPolicy: IfNotPresent
      tag: "1.7.8.11-apache"
    env:
      - name: PS_FOLDER_ADMIN
        value: "admin"
      - name: PS_FOLDER_INSTALL
        value: "install"
      - name: PS_DOMAIN
        value: "prestashop.example.com"
      - name: PS_INSTALL_AUTO
        value: "0"
    volumeMounts:
      - name: my-volume-name
        mountPath: /var/www/html
        subPath: prestashop/
    resources:
      limits:
        cpu: "375m"
        memory: 1Gi
      requests:
        cpu: 250m
        memory: 512Mi
```

I also tried checking if api.segment.io on port 80 was reachable with telnet, but it seems it's not. The only reachable port appears to be port 443.

Do you have any idea how I can resolve this issue? Until yesterday, I was able to install PrestaShop without problems.
I'm doing the installation through the guided setup at https://my.domain/install."

Thanks in advance for your help
