### ISSUE TITLE
Prestashop in kubernetes

### ISSUE THREAD

**Issue by Tedezed** [PrestaShop/docker#49]
Hi friends, I use your image of docker for deploy one prestashop with mysql.

```
- name: DB_USER
  value: root
 - name: DB_PASSWD
  value: pass
- name: PS_DEV_MODE
  value: "1"
- name: DB_SERVER
  value: 10.254.210.20
```

The application not reply to the browser, I think that redirection does not work. I enter with node port.

Minion --->`http://192.168.33.22:32444/install/`

#### Log of the pod
```
W1222 16:21:01.378497   19535 cmd.go:161] log is DEPRECATED and will be removed in a future version. Use logs instead.

* Waiting for confirmation of MySQL service startup

* Waiting for confirmation of MySQL service startup

* Reapplying PrestaShop files for enabled volumes ...

* Enabling DEV mode ...

* Almost ! Starting Apache now

AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.10.9. Set the 'ServerName' directive globally to suppress this message
AH00558: apache2: Could not reliably determine the server's fully qualified domain name, using 172.16.10.9. Set the 'ServerName' directive globally to suppress this message
[Thu Dec 22 16:10:36.534432 2016] [mpm_prefork:notice] [pid 1] AH00163: Apache/2.4.10 (Debian) configured -- resuming normal operations
[Thu Dec 22 16:10:36.534530 2016] [core:notice] [pid 1] AH00094: Command line: 'apache2 -D FOREGROUND'
172.16.10.1 - - [22/Dec/2016:16:10:37 +0000] "GET / HTTP/1.1" 302 226 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.16.10.1 - - [22/Dec/2016:16:10:38 +0000] "GET /install/ HTTP/1.1" 302 445 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.16.10.1 - - [22/Dec/2016:16:11:19 +0000] "GET /install/index.php?step=welcome HTTP/1.1" 302 376 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.16.10.1 - - [22/Dec/2016:16:12:00 +0000] "GET /install/index.php?step=welcome HTTP/1.1" 302 376 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
172.16.10.1 - - [22/Dec/2016:16:12:41 +0000] "GET /install/index.php?step=welcome HTTP/1.1" 302 376 "-" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:50.0) Gecko/20100101 Firefox/50.0"
```

Thx friends

**Comment by Tedezed** [comment]
#### Yaml PrestaShop
```
apiVersion: v1
kind: Service
metadata:
  name: mysql-ps
  labels:
    provider: mysql-ps
    heritage: helm
spec:
  clusterIP: 10.254.210.20
  ports:
  - port: 3306
  selector:
    provider: mysql-ps
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: mysql-ps
  labels:
    provider: mysql-ps
    heritage: helm
spec:
  replicas: 1
  template:
    metadata:
      labels:
        provider: mysql-ps
    spec:
      containers:
      - name: mysql-ps
        image: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: pass
        ports:
        - containerPort: 3306
---
apiVersion: v1
kind: Service
metadata:
  name: prestashop
  labels:
    app: prestashop
    heritage: helm
spec:
  type: NodePort
  ports:
    - port: 80
      protocol: TCP
      name: http
  selector:
    app: prestashop
---
apiVersion: v1
kind: ReplicationController
metadata:
  name: prestashop
  labels:
    app: prestashop
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: prestashop
    spec:
      containers:
      - name: prestashop
        image: prestashop/prestashop:1.7
        ports:
        - containerPort: 80
        env:
          - name: DB_USER
            value: root
          - name: DB_PASSWD
            value: pass
          - name: PS_DEV_MODE
            value: "1"
          - name: DB_SERVER
            value: 10.254.210.20
```
