### ISSUE TITLE
Installing prestashop is not possible when using a reverse proxy

### ISSUE THREAD

**Issue by yellowiscool** [PrestaShop/docker#63]
Hei,

I'm testing prestashop/prestashop:latest behind a reverse proxy (nginx-proxy), and the installDatabase operation timeouts after 30s (504 Gateway Time-out).

I guess I can restart the installation without a reverse proxy, but it's not very convenient.

**Comment by Quetzacoalt91** [comment]
Hello,

Without the reverse proxy, is the installDatabase step needs less than 30 seconds to be done ?
If no, then increasing you timeout values on your reverse proxy should be enough. Here a few directives I found for Nginx:
```
proxy_connect_timeout       300;
proxy_send_timeout          300;
proxy_read_timeout          300;
send_timeout                300;
```

**Comment by yellowiscool** [comment]
Yes thanks it solves the problem. But maybe Prestashop should not crash
when a timeout happens. Having to change this value isn't very user
friendly.

I know it's also not always possible to change the timeout delay, using
Amazon Cloudfront for example.

Le 14 mars 2017 8:46 AM, "Thomas N" <notifications@github.com> a écrit :

Hello,

Without the reverse proxy, is the installDatabase step needs less than 30
seconds to be done ?
If no, then increasing you timeout values on your reverse proxy should be
enough. Here a few directives I found for Nginx:

proxy_connect_timeout       300;
proxy_send_timeout          300;
proxy_read_timeout          300;
send_timeout                300;

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/PrestaShop/docker/issues/63#issuecomment-286357015>,
or mute
the thread

**Comment by Quetzacoalt91** [comment]
Unfortunately, even if the step complete itself after you got a timeout by the proxy, the installer is unable to know if it can send the next step, and when.

The real solution would be to improve the server performances, or to reduce the tasks to do during this step. ;)

**Comment by yellowiscool** [comment]
I know it will probably be on your lowest priority scale ever, but it could
be possible to create a temporary file when the action start, and remove it
(or write the error) when the action is done.

So if a timeout happen, you can periodically check whether this file exists
using Ajax, and know the status of the action.

**Comment by aleksander351** [comment]
@yellowiscool Hi, I am also having problems setting it up. I am using nginx-proxy and it works well with wordpress. I am not sure, what I am doing wrong with the Prestashop parameters.

`  prestashop:
    image: 'bitnami/prestashop:latest'
    environment:
      - MARIADB_HOST=mariadb
      - MARIADB_PORT_NUMBER=3306
      - PRESTASHOP_DATABASE_USER=xxx
      - PRESTASHOP_DATABASE_NAME=xxx
      - ALLOW_EMPTY_PASSWORD=yes
      - PRESTASHOP_HOST=xxxxx.net
      - VIRTUAL_HOST=xxxxx.net
      - LETSENCRYPT_HOST=xxxxx.net
      - LETSENCRYPT_EMAIL=xxxxx@gmail.com
    ports:
      - 8083:80
    volumes:
      - 'prestashop_data:/bitnami'
    depends_on:
      - mariadb`

**Comment by minhbxn** [comment]
me too! having the same problem ... prestashop + jwilder/nginx-proxy :D

**Comment by aleksander351** [comment]
@minhbxn  I was able to get it to work with mariadb instead of mysql and docker-compose version 3.

**Comment by clementduveau** [comment]
> @minhbxn I was able to get it to work with mariadb instead of mysql and docker-compose version 3.

Can you provide a solution ?

I use successfully Traefik on many containers but it doesn't work on PrestaShop.
I used this image and also the Bitnami image and I see that AFTER the installation is successful, PrestaShop is answering with HTTP 302 and give me its private IP adress. So the problem seems to come from the PrestaShop container itself.

Regards

**Comment by aleksander351** [comment]
`

    version: '3'
    services:
      mariadb:
        image: mariadb
        restart: unless-stopped
        environment:
          - MYSQL_ROOT_PASSWORD=xxxxxxx
          - MYSQL_DATABASE=aaaaaaaaaaa
          - MYSQL_USER=yyyyyyy
          - MYSQL_PASSWORD=xxxxxxx
        volumes:
          - /var/lib/docker/volumes/xxxxxxx-mysql:/var/lib/mysql
        container_name: xxxxxx
    
      prestashop:
        image: prestashop/prestashop
        restart: unless-stopped
        ports:
          - "8099:80"
        depends_on:
          - mariadb
        environment:
          - DB_SERVER=mysql
          - DB_USER=yyyyyyy
          - DB_PASSWD=xxxxxxx
          - DB_PREFIX=ps_
          - DB_NAME=aaaaaaaaaaa
          - ADMIN_MAIL=xxxxxxx@xxxxxx.com
          - ADMIN_PASSWD=xxxxxxxxxxxx
          - PS_DOMAIN=xxxxxxxx.com
          - VIRTUAL_HOST=www.xxxxxxxx.com,xxxxxxxx.com # replace with real domain
          - LETSENCRYPT_HOST=www.xxxxxxxx.com,xxxxxxxx.com # replace with real domain
          - LETSENCRYPT_EMAIL=xxxxxxxx@xxxxxxx.com # replace with real email
        volumes:
          - /var/lib/docker/volumes/yyyyyyy-presta:/var/www/html
        links:
          - mariadb
        container_name: yyyyyyy
    
    volumes:
      xxxxxxx-mysql:
        driver: local
      yyyyyyy-presta:
        driver: local
    
    networks:
      default:
        external:
          name: xsxsxsxsxs
    
    `

**Comment by clementduveau** [comment]
Hi,

It doesn't work on my installation. It is not the same of course (I don't use jwilder) but I still get the same error.
I see that you open the port of the container on your host
```
ports:
    - "8099:80"
```
Are you really going through your reverse-proxy / load-balancer ? In my case, the reverse-proxy is on the same host, so I don't expose the ports of the Prestashop container itself.

I may have found a solution involving modyfing the PHP code of Prestashop. I am currently investigating on it

Regards

**Comment by fif10** [comment]
Hi 

I think I managed today with : 

> presta -fpm
> nginx as web server front for presta

and then 
> nginx as proxy
> letencrypt companion 


(did not do it in detail, so certainly a few things can be improved and should be cleaned, but seems to work) 

For the first part : 
```

version: '3.2'
services:
  db:
#    build: .
    image: mariadb
    restart: always
    container_name: prestashop_mysite_maria
    environment:
      MYSQL_ROOT_PASSWORD: xxxx replace xxxx
    volumes:
     - /prestashopData/mariadb:/var/lib/mysql
     - /prestashopData/mariadb_conf:/etc/mysql/conf.d
    #ports:
    #  - 3307:3306
    networks:
      - proxy-tier




  presta_fpm:
    build:
      context: prestashop-fpm
#           If you want to change the prestashop user UID to match your local user UID
#           change it here and bellow
#           args:
#      UID: '1001'
    restart: always
    container_name: prestashop_mysite_fpm
    environment:
       PS_DOMAIN: test.mysite.org
       PS_INSTALL_AUTO: 0
    volumes:
      - /prestashopData/shop/:/prestashop/
    user: "1001"
#    volumes:
#        - type: bind
#          source: /prestashopData/shop
#          target: /var/www/html
    networks:
      - proxy-tier

  nginx:
        image: nginx:1.14.0-alpine
        container_name: prestashop_nginx
        ports:
            - "8086:80"
        volumes:
            - /prestashopData/shop/:/prestashop/
            - ./prestashop-nginx/prestashop-nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
          - "presta_fpm"
        networks:
          - proxy-tier

        environment:
          - VIRTUAL_HOST=test.mysite.org
          - VIRTUAL_NETWORK=nginx-proxy
          - VIRTUAL_PORT=8086
          - LETSENCRYPT_HOST=test.mysite.org
          - LETSENCRYPT_EMAIL=xxxx replace xxxx





networks:
  proxy-tier:
    external:
      name: nginx-proxy
```
`
for more details see 
https://github.com/PrestaShop/PrestaShop/tree/develop/docs/docker/nginx_fpm


For the proxy part : 
```
# proxy nginx with letsencrypt
#

version: '2'

services:
  proxy:
    image: jwilder/nginx-proxy
    container_name: proxy
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./proxy/conf.d:/etc/nginx/conf.d
      - ./proxy/vhost.d:/etc/nginx/vhost.d
      - ./proxy/html:/usr/share/nginx/html
      - ./proxy/certs:/etc/nginx/certs:ro
      - /var/run/docker.sock:/tmp/docker.sock:ro
    networks:
      - proxy-tier
    restart: always

  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-companion
    volumes_from:
      - proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./proxy/certs:/etc/nginx/certs:rw
    restart: always




networks:
  proxy-tier:
    external:
      name: nginx-proxy

```


Not sure if needed but on presta, I have multisite enabled / ssl enable (done that straight to db) / domain
