### ISSUE TITLE
After stopping docker container it won't start again

### ISSUE THREAD

**Issue by ddelizia** [PrestaShop/docker#7]
I made a simple prestashop docker installation, here my docker compose file:
```
  prestashop:
  image: prestashop/prestashop
  hostname: shop.deliziaalessandro.it
  ports:
    - "8081:80"
  links:
    - mysql:mysql
  environment:
    DB_SERVER: mysql
    DB_USER: mysql
    DB_PASSWD: mysql
    DB_NAME: mysql
    PS_LANGUAGE: it
    PS_COUNTRY: it'
````

it starts correctly but when I stop and restart it, then it shutdown right after the startup. Here is the only output log:

```
* Almost ! Starting Apache now

httpd (pid 10) already running
```

I stop/start the container like this:

```
docker start <containerName>
docker stop <containerName>
```
