### ISSUE TITLE
Cannot enable SSL

### ISSUE THREAD

**Issue by marceloschmidt** [PrestaShop/docker#84]
I'm running PrestaShop v 1.7.1.2 via Docker.

When I try to enable SSL, by clicking the "Please, click here to check if your store supports SSL", the browser correctly redirects to https and loads the admin, but it never passes the check. If I check my console for log messages I find this:
```
Mixed Content: The page at 'https://www.mydomain.com.br/admin..../index.php?controller=AdminPreferences&token=eeee....' was loaded over HTTPS, but requested an insecure image 'http://profile.prestashop.com/username%40domain.tld.jpg'. This content should also be served over HTTPS.
```
**Could this be the reason?**

If you need further information, read on :) 

I run PrestaShop with docker-compose. Here's the relevant part:

```
version: '2'
services:
  nginx:
    volumes:
      - /data/nginx:/etc/nginx/conf.d
      - /data/sites/:/sites
      - /data/nginx/dhparam.pem:/etc/nginx/ssl/dhparam.pem
      - /etc/letsencrypt/:/etc/letsencrypt/
    ports:
      - 80:80
      - 443:443
    restart: unless-stopped
    image: nginx

  mariadb:
    image: mariadb:10.1
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=xxx
      - MYSQL_DATABASE=xxx
      - MYSQL_USER=xxx
      - MYSQL_PASSWORD=xxx
    volumes:
      - /data/mysql/db:/var/lib/mysql

  prestashop:
    image: prestashop/prestashop
    ports:
      - 8081:80
    depends_on:
      - mariadb
```

As you can imagine, I use nginx as a reverse-proxy to my docker containers. 
Here's the nginx part for the prestashop container:
```
server {
	listen 80;
	server_name mydomain.com www.mydomain.com;

	location /.well-known {
		root /sites/letsencrypt;
	}

        location / {
		client_max_body_size 32m;
                proxy_buffering off;
                proxy_http_version 1.1;
                proxy_read_timeout 600;
                proxy_send_timeout 600;
                proxy_set_header   Host             $host;
                proxy_set_header   Referer          $http_referer;
                proxy_set_header   X-Real-IP        $remote_addr;
                proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
                proxy_set_header   Upgrade          $http_upgrade;
                proxy_set_header   Connection       "upgrade";
                proxy_set_header   X-Forward-Proto  http;
                proxy_set_header   X-Nginx-Proxy    true;
                proxy_redirect     off;
                proxy_pass         http://prestashop;
                if ($uri != '/') {
                        expires 30d;
                }
        }
}

server {
	listen 443;
	server_name mydomain.com www.mydomain.com;

	location /.well-known {
		root /sites/letsencrypt;
	}

	location / {
		client_max_body_size 32m;
		proxy_buffering off;
		proxy_http_version 1.1;
		proxy_read_timeout 600;
		proxy_send_timeout 600;
		proxy_set_header   Host             $host;
		proxy_set_header   Referer          $http_referer;
		proxy_set_header   X-Real-IP        $remote_addr;
		proxy_set_header   X-Forwarded-For  $proxy_add_x_forwarded_for;
		proxy_set_header   Upgrade          $http_upgrade;
		proxy_set_header   Connection       "upgrade";
		proxy_set_header   X-Forward-Proto  http;
		proxy_set_header   X-Nginx-Proxy    true;
		proxy_redirect     off;
		proxy_pass         http://prestashop;
		if ($uri != '/') {
			expires 30d;
		}
	}
	ssl on;

	ssl_certificate /etc/letsencrypt/live/mydomain.com/fullchain.pem;
	ssl_certificate_key /etc/letsencrypt/live/mydomain.com/privkey.pem;

	ssl_ciphers          'EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH';
	ssl_prefer_server_ciphers on;
	ssl_dhparam          /etc/nginx/ssl/dhparam.pem;
}
```

Hopefully that's enough information to get started ;)
